import type { Metadata } from "next";

import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "XCESS Luggage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`h-dvh w-full bg-white antialiased overflow-x-hidden`}>
        <div className="min-h-screen w-full">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
